### ISSUE TITLE
Download link in S3 Storage Folder returns 400

### ISSUE THREAD

**Issue by tennex-adam** [Study-Tracker/Study-Tracker#121]
Clicking the `Download` link in the dropdown of a file in an S3 Storage Folder returns a 400 response.

![image](https://github.com/Study-Tracker/Study-Tracker/assets/21001561/a31a00a0-3e03-4307-8277-3e88cee5b284)

The URL format of the GET made by the browser is `https://<domain.com>/api/internal/data-files/download?locationId=618&path=<path-to-file>/test-upload.txt`.

The front end is sending a query string [locationId](https://github.com/Study-Tracker/Study-Tracker/blob/f0bc3e0741670b99c43b2c2067b0c36037cfa553/client/src/common/fileManager/FileManagerTable.js#L154C98-L154C109), but the API is looking for [folderId](https://github.com/Study-Tracker/Study-Tracker/blob/f0bc3e0741670b99c43b2c2067b0c36037cfa553/web/src/main/java/io/studytracker/controller/api/internal/DataFileStoragePrivateController.java#L82).  I've confirmed that if we update the query string parameter, the file downloads as expected.

If this is as straightforward as it looks, I'm happy to drop a PR in. It looks like there are only two other pages that have commented code that would get updates.

**Comment by woemler** [comment]
Out of curiosity: was this download triggered from the File Manager page or the Files tab of a Study or Assay details page?

**Comment by tennex-adam** [comment]
It's triggered from the `Files` tab right when a study is first opened.

**Comment by woemler** [comment]
Thanks, I'll get a fix for this out ASAP.

**Comment by tennex-adam** [comment]
Thanks!  I just built off main and confirmed we're good.  I appreciate the quick turnaround!
