### ISSUE TITLE
Select Files upload button pops two file selection OS dialogs  

### ISSUE THREAD

**Issue by tennex-adam** [Study-Tracker/Study-Tracker#132]
When uploading a file, clicking Select Files pops two file selection dialogs.

![image](https://github.com/Study-Tracker/Study-Tracker/assets/21001561/cd4fe118-8279-44e1-b7f4-daed6677fb04)
![image](https://github.com/Study-Tracker/Study-Tracker/assets/21001561/a0647df6-2fac-49da-b585-d2217ca00610)

Issue created on behalf of @DavidSun89

**Comment by woemler** [comment]
@DavidSun89 What browser are you using? What OS?

**Comment by DavidSun89** [comment]
@woemler I am using Windows 10 and Chrome
