### ISSUE TITLE
Add navigation from Assay view back to list of Assays in a study

### ISSUE THREAD

**Issue by aksarkar** [Study-Tracker/Study-Tracker#166]
I navigate to the list of Assays under my study (for example, PI-218).

I want to mark an Assay (for example, PI-218-024) as completed, and then navigate back to the list of all Assays under the study (PI-218).

Right now, I need to do this in 2 clicks: one to the navigation breadcrumb for the study, and then another back to the list of Assays (where I just was to begin with).

It would be helpful to be able to do this in one click.

**Comment by woemler** [comment]
Navigation breadcrumb for study on the Assay Details page will now route back to the study details 'Assays' tab.
